import "dotenv/config";
import { Keypair } from "@solana/web3.js";
import bs58 from "bs58";
import { writeFileSync } from "fs";

interface WalletInfo {
  name: string;
  publicKey: string;
  secretKey: string;
}

async function main() {
  console.log("Setting up test wallets for OpenClaw Marketplace...\n");

  // Create wallets
  const wallets: WalletInfo[] = [
    { name: "Bot A (Requester)", ...createWallet() },
    { name: "Bot B (Worker)", ...createWallet() },
    { name: "Bot C (Worker 2)", ...createWallet() },
  ];

  // Display and save wallet info
  console.log("Generated Wallets:");
  console.log("==================\n");

  for (const wallet of wallets) {
    console.log(`${wallet.name}:`);
    console.log(`  Public Key:  ${wallet.publicKey}`);
    console.log(`  Secret Key:  ${wallet.secretKey.slice(0, 20)}...`);
    console.log();
  }

  // Note about SOL airdrops
  console.log("To fund these wallets with SOL (for transaction fees):");
  console.log("Visit https://faucet.solana.com and paste each public key.\n");

  // Save wallets to .env.local
  const envContent = `# Test wallets generated by setup-wallets.ts
# DO NOT commit this file!

# Bot A - Job requester
BOT_A_PUBLIC_KEY=${wallets[0].publicKey}
BOT_A_SECRET_KEY=${wallets[0].secretKey}

# Bot B - Worker
BOT_B_PUBLIC_KEY=${wallets[1].publicKey}
BOT_B_SECRET_KEY=${wallets[1].secretKey}

# Bot C - Worker 2
BOT_C_PUBLIC_KEY=${wallets[2].publicKey}
BOT_C_SECRET_KEY=${wallets[2].secretKey}
`;

  writeFileSync(".env.local", envContent);
  console.log("✓ Wallets saved to .env.local\n");

  // Instructions
  console.log("Next steps:");
  console.log("1. Fund wallets at https://faucet.solana.com (paste each public key)");
  console.log("2. Run 'npm run airdrop-usdc' to create test USDC");
  console.log("3. Run 'npm run dev' to start the marketplace server");
  console.log("\nNote: Keep .env.local private - it contains secret keys!");
}

function createWallet(): { publicKey: string; secretKey: string } {
  const keypair = Keypair.generate();
  return {
    publicKey: keypair.publicKey.toBase58(),
    secretKey: bs58.encode(keypair.secretKey),
  };
}

main().catch(console.error);
